# docker compose version
version: '3.8'
# all the containers have to declare inside services
services:
  rabbitmq-base:
    container_name: rabbitmq-base
    image: rabbitmq-base
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      taxnet-net:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    ports:
      - ${APP_HTTP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  warehouse-migration:
    image: rabbitmq-base
    env_file:
      - .env
    command: npm run migrate:run
    networks:
      - taxnet-net

networks:
  taxnet-net:
    name: ${TAXNET_NET_NAME}
    external: true

# save (persist) data
volumes:
  db_data: {}
