version: '3.8'

services:
  warehouse-service:
    container_name: local-warehouse-service
    image: warehouse-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    networks:
      taxnet-net:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    command: npm run start:dev
    ports:
      - ${APP_HTTP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  taxnet-net:
    name: ${TAXNET_NET_NAME}
    external: true
